application: diary
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: assets/templates/index.html
  upload: assets/templates/index.html

- url: /js
  static_dir: assets/js/
- url: /lib
  static_dir: assets/lib/
- url: /templates
  static_dir: assets/templates/
- url: /nls
  static_dir: assets/nls

- url: /.*
  script: _go_app
